###
GET http://localhost:8000/

###
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username" : "gilgamesh@gmail.com",
    "password" : "123123123"
}

###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username" : "gilgamesh@gmail.com",
    "password" : "123123123"
}
###

